### ISSUE TITLE
https://github.com/buzz-lang/Buzz relation / conflict?

### ISSUE THREAD

**Issue by shinebayar-g** [buzz-language/buzz#106]
Not sure anyone is aware of it. There is already a programming language called Buzz. https://github.com/buzz-lang/Buzz
Would there be any conflicting issues or concerns around this?

_Probably should've opened a discussion. Pls feel free to move it._

**Comment by giann** [comment]
Not sure how much this is an issue. They seem to have a completely different goal. I'll reach out to them but I doubt they care.

**Comment by shinebayar-g** [comment]
Yeah, but from the SEO perspective it isn't great to have a duplicate name at this point. They've quite years of development already.

**Comment by giann** [comment]
Time will tell, but it's a little late to consider changing name :)
