### ISSUE TITLE
wasm web/wasi target

### ISSUE THREAD

**Issue by giann** [buzz-language/buzz#142]
Probable issues:
- Disable mimalloc
- Expose JS regex in place of libpcre
- Disable JIT and FFI
- VM tail call not supported: the VM does not uses a big switch to dispatch opcode but tailcalls, this does not seem to be supported by llvm_stage2 for the wasm64-wasi target
- We can keep 64bit NaN boxing but it might have a performance impact
- We can't use dynamic library loading but we don't really need it: statically link std libs and import does only buzz definition importing
- Disable os specific std libs: fs, io, os, ffi

Resources:
- https://dev.to/sleibrock/webassembly-with-zig-part-1-4onm
- [Example of exposing js function to wasm module](https://github.com/190n/rafsort/blob/bf82a14e1d409796d93eac9b485417f2c5b26ea7/src/worker/worker.ts#L46-L64)
- Bring your own os: [zig](https://github.com/castholm/wasm-sliding-puzzle/blob/0ef992a5b5d7b9eeadd3d525d2e78eb83f955a6c/src/main.zig#L64-L99), [js](https://github.com/castholm/wasm-sliding-puzzle/blob/0ef992a5b5d7b9eeadd3d525d2e78eb83f955a6c/src/Stderr.ts)
- https://github.com/mitchellh/zig-js

**Comment by giann** [comment]
https://dev.to/sleibrock/webassembly-with-zig-part-1-4onm

**Comment by giann** [comment]
[Example of exposing js function to a wasm module](https://github.com/190n/rafsort/blob/bf82a14e1d409796d93eac9b485417f2c5b26ea7/src/worker/worker.ts#L46-L64)

**Comment by judah-caruso** [comment]
Are there any plans for compiling buzz to wasm directly? Assuming this ticket is to just allow the buzz interpreter to run within wasm?

**Comment by giann** [comment]
Not sure what you mean? buzz can only run within wasm if built for wasm.

**Comment by giann** [comment]
Yes this is out of scope. That would require buzz to become an AOT compiled language.

**Comment by giann** [comment]
Reopening because of https://ziglang.org/download/0.12.0/release-notes.html#Bring-Your-Own-OS-API-Layer-Regressed which effectively kills this feature
