### ISSUE TITLE
Don't handle `OutOfMemory` errors

### ISSUE THREAD

**Issue by giann** [buzz-language/buzz#159]
We could get rid of 70% of error handling code in buzz if we just `@panic` when `OutOfMemory`.
I see no value in handling those.

**Comment by daurnimator** [comment]
I'm totally out of the loop on buzz right now; but being able to handle Out Of Memory is invaluable.

**Comment by giann** [comment]
I don't know. In a garbage collected language what could you do to recover memory? Isn't it pretty much game over when you're out of memory?

**Comment by daurnimator** [comment]
> In a garbage collected language what could you do to recover memory?

  - Run an emergency garbage collection
  - Defragment some memory

> Isn't it pretty much game over when you're out of memory?

If you fail to do either of the above (or don't want to), then throw an error.
Throwing the error will unwind the stack to the next `try`/`catch` and probably free up some references to some objects that can now be freed.

Now in a CLI tool there there might not be a `try`/`catch` other than simply printing the error and exiting.
But in e.g.
  - a game you might drop the current frame; or limit the render distance
  - a http server you might drop the current request
  - a job queue you might requeue the current job and try a different one
