### ISSUE TITLE
Unavoidable syntax warning from main signature?

### ISSUE THREAD

**Issue by Costava** [buzz-language/buzz#184]
I ran the SDL example given in the repo:

```
$ ./zig-out/bin/buzz examples/sdl.buzz 

examples/sdl.buzz:5:16: [W89] Syntax warning: Unused local of type `[str]`
     3 ╭─ 
     4 │  | buzz -L/path/to/SDL2.dylib/so/dll examples/sdl.buzz
     5 │  fun main([str] args) > int !> SDLError {
       ┆                 ╭───
       ┆                 ╰─ Unused local of type `[str]`
     6 │      SDL sdl = SDL.init([Subsystem.Video]);
     7 ╰─ 
```

And got a warning that the `args` argument to `main` is unused.
Removing the parameter causes a fatal syntax error, which matches [what the Guide says](https://buzz-lang.dev/guide/functions.html#main) is permitted as the signature of main.

**Is there a canonical way to avoid the 'unused' syntax warning?**

(Tested with buzz at commit eb4e8ad220efbc7fa778e3bbf3e85d4fd942ed52)

**Comment by giann** [comment]
Yes you can name the argument `_`:
```buzz
fun main([str] _) > void {
}
```

This is not yet documented
