### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by sneekyfoxx** [buzz-language/buzz#190]
## Linux Version
6.5.4-arch2-1

## Zig Version
0.12.0-dev.587+eb072fa52

## Patch
`mimalloc` installs header files to `/use/local/include/mimalloc-2.1` when using `sudo make install` but `src/mimalloc.zig` only tries to include `mimalloc.h`. The full path to mimalloc.h must be supplied in order for it to work.

**Comment by giann** [comment]
What command did you use to build then run buzz?
