### ISSUE TITLE
Loop labels

### ISSUE THREAD

**Issue by giann** [buzz-language/buzz#199]
To allow breaking outer loops:
```buzz
while :outer (true) {
    while (true) {
        break outer;
    }
}
```

**Comment by kfird214** [comment]
Because I think this project is drawing inspiration from zig I think it should just be the same as zig [Labeled-while](https://ziglang.org/documentation/master/#Labeled-while)

```zig
outer: while (true) {
  while (true) {
    if (mabe_break_inner_loop) break;
    if (mabe_break_outer_loop) break :outer;
  }
}
```

**Comment by giann** [comment]
buzz is not really inspired by zig even though it's implemented with it. It takes more from Dart, Swift and Lua (for its architecture).

I think that starting with the label let it seem like a label could appear anywhere.
