### ISSUE TITLE
Argument/Property name can be omitted if variable passed has same name

### ISSUE THREAD

**Issue by giann** [buzz-language/buzz#204]
buzz only allows the first argument of a function to be unnamed. I stand by that choice but sometimes, named argument can be a little repetitive if the value passed has the same name.

With this, we would go from:
```buzz
fun hello(str firstname, str lastname, int age) > void {
    | ...
}

hello(firstname, lastname: lastname, age: calculatedAge);
```

to:
```buzz
fun hello(str firstname, str lastname, int age) > void {
    | ...
}

hello(firstname, lastname, age: calculatedAge);
```

We can do the same for object initialization (like rust):
```buzz
object Person {
    str firstname,
    str lastname,
    int age,
}

var person = Person{
    firstname,
    lastname,
    age = calculatedAge
}
```

**Comment by matdexir** [comment]
That's a good one! It really makes the language feel more natural.
