### ISSUE TITLE
build error zig 11

### ISSUE THREAD

**Issue by ThanosYeah** [buzz-language/buzz#209]
I use zig 11 and use nix-os,when i try to zig build run --game-of-life.buzz it shows this:/buzz/build.zig:527:8: error: member function expected 2 argument(s), found 1
    lib.addCSourceFiles(
    ~~~^~~~~~~~~~~~~~~~
/nix/store/6vgflg2gmqs0cn6n3h2npimfcybizwwp-zig-0.11.0/lib/zig/std/Build/Step/Compile.zig:891:5: note: function declared here
pub fn addCSourceFiles(self: *Compile, files: []const []const u8, flags: []const []const u8) void {
~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    build: /home/debian/Desktop/CustomCli/buzz/build.zig:269:27
    runBuild__anon_7165: /nix/store/6vgflg2gmqs0cn6n3h2npimfcybizwwp-zig-0.11.0/lib/zig/std/Build.zig:1639:37
    remaining reference traces hidden; use '-freference-trace' to see all reference traces note(i have already done everything that is says for building/developing in the landing page of the repo)

**Comment by giann** [comment]
You have to use the nightly build of zig.

build.zig should have complained about it.

**Comment by ThanosYeah** [comment]
Sorry,(I am new to zig,the question may sound dumb)how to use the nightly build of zig(i have installed the 

zig-linux-x86_64-0.12.0-dev.899+027aabf49.tar.xz
--) is it nightly or do i have to do something else

**Comment by giann** [comment]
Yes you take the download under the "master" section

**Comment by giann** [comment]
If you're under linux x86_64 a binary of buzz is available on the 0.3.0 release

**Comment by ThanosYeah** [comment]
i did install it from there and then did the same command and it shows me the same error(what to do?),Also  you should make the binary  which the user can download in tag 3.0 nix friendly cause it might be hard-coded,it shows this:Warning: execve: No such file or directory which is a common sign of hard-coded program

**Comment by giann** [comment]
I don't know what you mean by hard-coded?
Maybe the latest zig build has a change, let me check.

**Comment by ThanosYeah** [comment]
> I don't know what you mean by hard-coded?
> 
> If you have the same error you must not be using the correct version of zig still: you can see [here](https://github.com/ziglang/zig/blob/027aabf4977d0362e908d9ef732aaa929605d563/lib/std/Build/Step/Compile.zig#L937) that `addCSourceFiles` expects 1 argument.

What version of zig do you use? Also when I say it is hard coded it links to files that nix doesn't have but other Linux have more detailed for full explanation:https://discourse.nixos.org/t/dolphin-cant-find-execvp-and-bash-cant-find-the-script-i-ask-it-to-execute/21338

**Comment by giann** [comment]
I use the one you mentioned: 0.12.0-dev.899+027aabf49

**Comment by ThanosYeah** [comment]
> I use the one you mentioned: 0.12.0-dev.899+027aabf49

I don't know why,I will try to compile zig myself and use a vm.Should I close the issue?

**Comment by giann** [comment]
Can you try outside of nix?
Seems like you installed zig 0.11 and then 0.12 but it's still using 0.11?

We can continue the discussion on [Discord](https://discord.gg/VnMdNSdpNV) if you want.

**Comment by ThanosYeah** [comment]
Resolved:use nix shell 'github:mitchellh/zig-overlay#master' it installs latest zig version including nightly
