### ISSUE TITLE
REPL crashes out when encountering an undefined value.

### ISSUE THREAD

**Issue by matdexir** [buzz-language/buzz#220]
This is what happens when the variable is defined

![2023-10-21_15-33](https://github.com/buzz-language/buzz/assets/58453130/21358e97-d198-4976-aa17-964eadaa0418)

This is what happens when it is undefined
![2023-10-21_15-33_1](https://github.com/buzz-language/buzz/assets/58453130/18b7929b-4eaf-43cb-96b9-69850ee57b28)

**Comment by matdexir** [comment]
I also realized that it segfaults when I send Ctrl+C or Ctrl+D.

**Comment by giann** [comment]
> I also realized that it segfaults when I send Ctrl+C or Ctrl+D.

Yes this is linenoise. I plan on replacing it with readline or my own.
