### ISSUE TITLE
REPL Panic when user forgets the beginning single quote of a char

### ISSUE THREAD

**Issue by matdexir** [buzz-language/buzz#222]
Exhibit 1
![2023-10-21_22-27](https://github.com/buzz-language/buzz/assets/58453130/dcfb7dc2-6325-4a20-ad98-586edd2150ef)

Exhibit 2
![2023-10-21_22-32](https://github.com/buzz-language/buzz/assets/58453130/54bd0c74-caa7-48ff-9234-6bd151bfa6ed)

**Comment by giann** [comment]
Fixed by https://github.com/buzz-language/buzz/commit/4b311bef43f493382f5dde2cdbf12369844ff9a3
