### ISSUE TITLE
Invalid Field Access: lib.target

### ISSUE THREAD

**Issue by sneekyfoxx** [buzz-language/buzz#243]
#### Bug: attempting to access a field that isn't a member of the *Step.Compile struct
![buzz-build](https://github.com/buzz-language/buzz/assets/100389302/b36a87b2-c8e8-4916-b527-5c190e8ec9f9)

**Comment by giann** [comment]
As i'm rewriting the AST right now i have not kept up with zig nightly in a long time
This will likely been adressed once i merge my work.
