### ISSUE TITLE
is buzz has real thread?

### ISSUE THREAD

**Issue by acodervic** [buzz-language/buzz#288]
is buzz has real thread?
There are many excellent script language such as LUAJIT, but Luajit is deadly without multi -threaded support, which makes it impossible to complete the more complicated application.

**Comment by giann** [comment]
It's planned: https://github.com/buzz-language/buzz/issues/176

**Comment by acodervic** [comment]
> It's planned: #176

Thank you for your answer, another question? How big is the execution file compiled by Buzz? I downloaded version 0.3 and found that Buzz has a large number of executable files .buzz is about 8m large. I want to say that this volume is too large. As a script language, there are only about 500K

**Comment by acodervic** [comment]
I think if Buzz cannot be kept very small, there is no big advantage compared to some other technologies (Graalvm Native). Sometimes I want to write some very small programs to distribute it, but I want the development of script language again efficiency

**Comment by acodervic** [comment]
sorry , I strip my buzz , it is only 1m . Thanks !

**Comment by giann** [comment]
buzz is not a compiled language. The executable is around 700kb if you build it with `-Doptimize=ReleaseSmall`.
