### ISSUE TITLE
Usage in serious projects

### ISSUE THREAD

**Issue by notramo** [buzz-language/buzz#293]
Is it suitable for any serious project?

The guide [Introduction](https://buzz-lang.dev/guide/) chapter says it **started** as a toy language:
> Buzz is a small/lightweight statically typed scripting language written in [Zig](https://ziglang.org/). It started as a toy language following the excellent book [Crafting Interpreters](https://craftinginterpreters.com/) by Robert Nystrom.

However, there is no mention where it is currently regarding the "toy language" status.

If it's suitable for serious projects, the quoted sentence can be a little bit off-putting for some devs who want to consider it, so I suggest rephrasing it.

**Comment by giann** [comment]
Until 1.0, which is pretty far out, buzz should not be considered for production work no.
